# Generated by Django 4.2.2 on 2023-06-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_hashtag_product_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hashtag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hashtags',
            new_name='categories',
        ),
    ]
